#!/usr/bin/env sh
set -eu
script_directory="$(dirname "$0")"
cd "$script_directory/../"

tag="latest"
case "${GITHUB_REF:-}" in "refs/tags/"*)
	tag="${GITHUB_REF#refs/tags/}"
esac

docker build --tag "chrisgavin/sosume:$tag" .
